gchar *id;
        gchar *display_name;
        gboolean organizer;
        gboolean self;
        gboolean resource;
        gboolean optional;
        gchar *response_status;
        gchar *comment;
        gchar *additional_guests;